name = "the-drawer"
main = "src/worker.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "dist"

[[kv_namespaces]]
binding = "DRAWER_KV"
id = "bf2c9f4cac1e45d79199d4f0d1dedaab"

[[kv_namespaces]]
binding = "OAUTH_KV"
id = "b87600ea20374cb58c61c3dddbed68f6"

[vars]
CF_ACCESS_TEAM = "aleozlx"
CF_ACCESS_AUD = "e3fb9826-5420-402d-bf74-6d39dc09682b"
