name = "the-drawer-mcp"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "DRAWER_KV"
id = "bf2c9f4cac1e45d79199d4f0d1dedaab"

[[kv_namespaces]]
binding = "OAUTH_KV"
id = "b87600ea20374cb58c61c3dddbed68f6"
